import 'package:electrocode_engine/electrocode_engine.dart';

ProjectInput completeBungalow({
  double area = 120,
  double heating = 15000,
  double range = 12000,
  double dryer = 5500,
  double waterHeater = 4500,
  double? evAmps,
  bool? evEms,
  double? evManaged,
  double? amperage = 200,
  ConductorMaterial material = ConductorMaterial.copper,
  double length = 20,
  GroundingElectrode electrode = GroundingElectrode.rods,
  List<SubPanelInput> subPanels = const [],
  Map<String, dynamic> additional = const {},
  BuildingType type = BuildingType.residential,
  String name = 'Bungalow QC',
  String? forcedServiceConductorSize,
  int dwellingUnits = 1,
}) {
  return ProjectInput(
    projectName: name,
    buildingType: type,
    description: 'Logement unifamilial Québec',
    voltage: '120/240',
    amperage: amperage,
    phases: 1,
    livingAreaM2: area,
    dwellingUnits: dwellingUnits,
    heatingType: HeatingType.electric,
    heatingWatts: heating,
    acWatts: 0,
    rangeWatts: range,
    dryerWatts: dryer,
    waterHeaterWatts: waterHeater,
    evChargerAmps: evAmps,
    evEnergyManagement: evEms,
    evManagedWatts: evManaged,
    newConstruction: true,
    serviceMaterial: material,
    forcedServiceConductorSize: forcedServiceConductorSize,
    serviceLengthM: length,
    conduitType: ConduitType.emt,
    groundingElectrode: electrode,
    subPanels: subPanels,
    additionalInfo: {
      if (evAmps == null && evEms == null) 'ev_none': true,
      ...additional,
    },
  );
}
